### ISSUE TITLE
How to compile the code

### ISSUE THREAD

**Issue by farzadmech88** [AndreaDesan/pimpleTKEBudgetFoam#3]
Hello Andrea
Thanks for you useful code which makes life much easier for us. Could you please give a Allwmake file and also how to integrate it with my original code(which is MPPICFOAM)? 
Should I just write "wmake libso src" or what? 

Thanks, 
Farzad

**Comment by farzadmech88** [comment]
Actually I cannot use the code directly since I need to change many things in my solver, so I decided to implement your code inside inside my solver. I am a little confused about tensor multiplication so I asked it in this thread in cfdOnline;

https://www.cfd-online.com/Forums/openfoam-post-processing/239404-how-calculate-dissipation-rate-openfoam.html#post815739

Could you please answer my question?

Thanks,
Farzad

**Comment by AndreaDesan** [comment]
Just a simple `wmake` (`wmake libso` is meant to be used to compile libraries, but for applications such as this one just `wmake` is fine) is enough to compile the solver. I can't comment on how to integrate this in your original code so I will close this issue.

Andrea
